CREATE DATABASE IF NOT EXISTS INOTES;

USE INOTES;

DROP TABLE IF  EXISTS USERS;
CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) UNIQUE,
    FIRST_NAME VARCHAR(255) ,
    LAST_NAME VARCHAR(255),
    MOBILE VARCHAR(15),
    PASSWORD VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

DROP TABLE IF EXISTS NOTES;
CREATE TABLE NOTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    NOTE TEXT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE 
);